name: "Cloudflare Cache Purge Action"
description: "A GitHub Action to purge Cloudflare's cache of your site"
author: "Nathan Vaughn"
inputs:
    cf_zone:
        description: "Cloudflare Zone"
        required: false
    cf_auth:
        description: "Cloudflare Authentication Key"
        required: false
    urls:
        description: "URLs to purge"
        required: false
    files:
        description: "Files to purge"
        required: false
    tags:
        description: "Cache-Tags to purge"
        required: false
    hosts:
        description: "Hosts to purge"
        required: false
    prefixes:
        description: "Prefixes to purge"
        required: false
    python:
        description: "Python interpreter to use"
        required: false
        default: python

branding:
    icon: "cloud"
    color: "orange"

runs:
    using: composite
    steps:
      - name: "Purge Cloudflare Cache"
        shell: bash
        run: ${{ inputs.python }} ${{ github.action_path }}/main.py --cf-zone="${{ inputs.cf_zone }}" --cf-auth="${{ inputs.cf_auth }}" --urls "${{ inputs.urls }}" --files "${{ inputs.files }}" --tags "${{ inputs.tags }}" --hosts "${{ inputs.hosts }}" --prefixes "${{ inputs.prefixes }}"
